pois:
  H:
    center: [0, 0]
obstructions: {}
hazards: {}
power_draws: {}
area: mdrs
mode: mdrs
robot_name: case
record_path: ./data
map_path: ./imgs/display_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: ET-GOA
latitude_center: 40.01045433
longitude_center: 105.24432153
capture_dist: 0.5
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [2.0, 2.0, 1.0, 1.0]
batt_drain_anomaly: 0.01388888
num_backup_batteries: 10
speed_anomaly: 0.25
available_pois: [H]
show_surveys: [true, true, true, true]
training: false
map: s1
