pois:
  A:
    center: [1.5, 6]
  H:
    center: [2.5, 0]
obstructions:
  o1:
    center: [4, 5]
    radius: 1
    effect: 1
    visible: true
  o2:
    center: [3, 6]
    radius: 1
    effect: 1
    visible: true
  o3:
    center: [1, 9]
    radius: 1
    effect: 1
    visible: true
  o4:
    center: [0, 8]
    radius: 1
    effect: 1
    visible: true
  o5:
    center: [-1, 0]
    radius: 1
    effect: 1
    visible: true
  o6:
    center: [0, 1]
    radius: 1
    effect: 1
    visible: true
  o7:
    center: [0.5, 2]
    radius: 1
    effect: 1
    visible: true
hazards: {}
power_draws: {}
area: gazebo
mode: cu
robot_name: case
record_path: ./data
map_path: ./imgs/display_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: ET-GOA
latitude_center: 40.01045433
longitude_center: 105.24432153
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [1.5, 1.5, 0.5, 1.5]
batt_drain_anomaly: 0.05
num_backup_batteries: 10
speed_anomaly: 0.25
available_pois: [A, B, C, D]
show_surveys: [true, true, true, true]
training: false
