pois:
  A:
    center: [1, 9]
  B:
    center: [4, 7]
  H:
    center: [2.5, 0]
obstructions:
  o1:
    center: [4, 5]
    radius: 1
    effect: 1
    visible: true
  o2:
    center: [1, 7]
    radius: 1.2
    effect: 1
    visible: true
  o3:
    center: [-0.5, 6.5]
    radius: 1
    effect: 1
    visible: true
hazards:
  h1:
    center: [2, 2]
    radius: 1
    effect: 0.005
    visible: true
power_draws:
  b1:
    center: [-1, 3]
    radius: 1
    effect: 5.0
    visible: true
area: gazebo
mode: cu
robot_name: case
record_path: ./data
map_path: ./imgs/display_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: CONDITION
latitude_center: 40.01045433
longitude_center: 105.24432153
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [1.5, 1.5, 0.5, 1.5]
batt_drain_anomaly: 0.05
num_backup_batteries: 10
speed_anomaly: 0.25
available_pois: [A, B, C, D]
show_surveys: [true, true, true, true]
training: false
map: s1
