pois:
  A:
    center: [-1.5, 9]
  B:
    center: [4.5, 7]
  C:
    center: [-1.5, 2]
  H:
    center: [2.5, 0]
obstructions:
  o1:
    center: [4, 5]
    radius: 1
    effect: 1
    visible: true
  o2:
    center: [3, 6]
    radius: 1
    effect: 1
    visible: true
  o3:
    center: [1, 9]
    radius: 1
    effect: 1
    visible: true
  o4:
    center: [0, 8]
    radius: 1
    effect: 1
    visible: true
  o5:
    center: [-1, 0]
    radius: 1
    effect: 1
    visible: true
  o6:
    center: [0, 1]
    radius: 1
    effect: 1
    visible: true
  o7:
    center: [0.5, 2]
    radius: 1
    effect: 1
    visible: true
hazards:
  h1:
    center: [3.2, 7.2]
    radius: 0.5
    effect: 0.005
    visible: true
  h2:
    center: [ 2.5, 7.5 ]
    radius: 0.5
    effect: 0.005
    visible: true
  h3:
    center: [ 3, 8.2 ]
    radius: 0.5
    effect: 0.005
    visible: true
  h4:
    center: [-0.5, 6]
    radius: 1.0
    effect: 0.005
    visible: false
power_draws:
  b1:
    center: [-1, 3]
    radius: 1
    effect: 5.0
    visible: true
area: gazebo
mode: cu #mdrs or cu
robot_name: case
record_path: ./data
map_path: ./imgs/display_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: TELEM
latitude_center: 40.01045433
longitude_center: 105.24432153
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [1.5, 1.5, 0.5, 1.5]
batt_drain_anomaly: 0.05
num_backup_batteries: 10
speed_anomaly: 0.25
available_pois: [A, B]
show_surveys: [true, true, true, true]
training: true
