pois:
  A:
    center: [1.0, 9.25]
  B:
    center: [4.25, 6]
  C:
    center: [0.25, 3]
  H:
    center: [2.5, 0]
obstructions:
# left side obstacles
  o1:
    center: [3, 5.5]
    radius: 0.6
    effect: 1
    visible: true
  o2:
    center: [3.5, 4.75]
    radius: 0.6
    effect: 1
    visible: true
  o11:
    center: [4.5, 4.75]
    radius: 0.6
    effect: 1
    visible: true
  o12:
    center: [3.25, 5.25]
    radius: 0.6
    effect: 1
    visible: true
# top obstacles
  o9:
    center: [2.75, 9.25]
    radius: 0.6
    effect: 1
    visible: true
  o8:
    center: [2.25, 8.25]
    radius: 0.6
    effect: 1
    visible: true
  o3:
    center: [1.5, 7.5]
    radius: 0.5
    effect: 1
    visible: true
  o10:
    center: [2, 7.5]
    radius: 0.4
    effect: 1
    visible: true
  o4:
    center: [0.75, 7.5]
    radius: 0.5
    effect: 1
    visible: true
# right side low obstacles
  o5:
    center: [0, 1.75]
    radius: 0.6
    effect: 1
    visible: true
  o6:
    center: [0.75, 2]
    radius: 0.6
    effect: 1
    visible: true
  o7:
    center: [1.25, 2.25]
    radius: 0.6
    effect: 1
    visible: true
hazards:
  h1:
    center: [3.2, 6.5]
    radius: 0.5
    effect: 0.005
    visible: true
  h2:
    center: [ 2.5, 6.5 ]
    radius: 0.5
    effect: 0.005
    visible: true
  h3:
    center: [ 3, 7.5]
    radius: 0.5
    effect: 0.005
    visible: true
  h4:
    center: [0.5, 6.25]
    radius: 1.0
    effect: 0.005
    visible: false
power_draws:
  b1:
    center: [0.5, 3.5]
    radius: 1
    effect: 5.0
    visible: true
area: aspen
mode: cu #mdrs or cu
robot_name: case
record_path: ./data
map_path: ./imgs/display_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: TELEM
latitude_center: 40.01045433
longitude_center: 105.24432153
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [1.5, 1.5, 0.5, 1.5]
batt_drain_anomaly: 0.05
num_backup_batteries: 10
speed_anomaly: 0.25
available_pois: [A, B, C]
show_surveys: [true, true, true, true]
training: true
map: m1
