pois:
  A:
    center: [1.0, 9.25]
  B:
    center: [4.25, 6]
  C:
    center: [0.25, 3]
  H:
    center: [4, 0]
obstructions:
# left side obstacles
  o1:
    center: [3, 5.5]
    radius: 0.6
    effect: 1
    visible: true
  o2:
    center: [3.5, 4.75]
    radius: 0.6
    effect: 1
    visible: true
  o11:
    center: [4.5, 4.75]
    radius: 0.6
    effect: 1
    visible: true
  o12:
    center: [3.25, 5.25]
    radius: 0.6
    effect: 1
    visible: true
# top obstacles
  o9:
    center: [2.75, 9.25]
    radius: 0.6
    effect: 1
    visible: true
  o8:
    center: [2.25, 8.25]
    radius: 0.6
    effect: 1
    visible: true
  o3:
    center: [1.5, 7.5]
    radius: 0.5
    effect: 1
    visible: true
  o10:
    center: [2, 7.5]
    radius: 0.4
    effect: 1
    visible: true
  o4:
    center: [0.75, 7.5]
    radius: 0.5
    effect: 1
    visible: true
# right side low obstacles
  o5:
    center: [0, 1.75]
    radius: 0.6
    effect: 1
    visible: true
  o6:
    center: [0.75, 2]
    radius: 0.6
    effect: 1
    visible: true
  o7:
    center: [1.25, 2.25]
    radius: 0.6
    effect: 1
    visible: true
  o13:
    center: [4.5, 2.5]
    radius: 0.7
    effect: 1
    visible: true
  o14:
    center: [0, 4.8]
    radius: 0.6
    effect: 1
    visible: true
  o15:
    center: [1, 4.5]
    radius: 0.5
    effect: 1
    visible: true
  o17:
    center: [-0.3, 6.5 ]
    radius: 0.3
    effect: 1
    visible: true
  o18:
    center: [3, 10 ]
    radius: 0.5
    effect: 1
    visible: true
hazards:
  h1:
    center: [3.2, 6.5]
    radius: 0.25
    effect: 0.005
    visible: true
  h2:
    center: [ 2.2, 6.8 ]
    radius: 0.25
    effect: 0.005
    visible: true
  h3:
    center: [ 3, 7.5]
    radius: 0.25
    effect: 0.005
    visible: true
  h4:
    center: [ 4, 7]
    radius: 0.25
    effect: 0.005
    visible: true
  h5:
    center: [ 3.5, 7.5]
    radius: 0.25
    effect: 0.005
    visible: true
  #h10: # unknown obstacle top
  #  center: [0.5, 6.25]
  #  radius: 1.5
  #  effect: 0.005
  #  visible: false
power_draws:
  b1:
    center: [1.6, 3.2]
    radius: 0.3
    effect: 10.0
    visible: true
  b2:
    center: [1.2, 3.5]
    radius: 0.3
    effect: 10.0
    visible: true
  b3:
    center: [0.7, 3 ]
    radius: 0.3
    effect: 10.0
    visible: true
  b4:
    center: [-0.7, 7.5 ]
    radius: 0.3
    effect: 10.0
    visible: true
  b5:
    center: [-0.3, 6.5 ]
    radius: 0.3
    effect: 10.0
    visible: true
  b6:
    center: [0.6, 7.4 ]
    radius: 0.3
    effect: 10.0
    visible: true
  #b10: # unknown obstacle bottom
  #  center: [3.5, 2.5]
  #  radius: 1.5
  #  effect: 10.0
  #  visible: false
area: aspen
mode: cu #mdrs or cu
robot_name: case
record_path: ./data
map_path: ./imgs/display_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: CONDITION
latitude_center: 40.01045433
longitude_center: 105.24432153
capture_dist: 0.25
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [0.75, 0.75, 0.2, 0.5]
batt_drain_anomaly: 0.05
num_backup_batteries: 10
speed_anomaly: 0.25
available_pois: [A, B, C]
show_surveys:
  pre-planning: false
  post-planning: false
  post-mission: false
  usability: false
training: false
map: m1
