obstructions:
  o1:
  - [10, 15]
  - [2]
  - 1
  o2:
  - [4, -5]
  - [5]
  - 1
  o3:
  - [12, 21]
  - [2.5]
  - 1
hazards:
  h1:
  - [-5, -15]
  - [2.5]
  - 0.25
power_draws:
  b1:
  - [-8, 0]
  - [5]
  - 1.5
  b2:
  - [-12, 5]
  - [5]
  - 1.5
record_path: ./data
map_path: ./imgs/mission_area.png
logo_path: ./imgs/logo.png
rollout_path: /data/webots/rollout{}_state.npy
condition: TELEM
latitude_center: 40.01045433
longitude_center: 105.24432153
anomalies: false
et_goa_threshold: 0.05
et_goa_stds: [1.5, 1.5, 0.5, 1.5]
batt_drain_rate: 0.5
show_surveys: false
